language: node_js
node_js: stable

git:
  depth: false

install:
  - npm install
  - chmod -R 777 ./node_modules/vuepress/
  - git clone https://github.com/davisp/ghp-import.git /tmp/ghp-import

script:
  - npm run build

deploy:
  provider: script
  script: ./.deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
